###########################################################################################
#
#  DEV ENVIRONMENT VARIABLES
#
###########################################################################################

# Just an example use case
# enable_analytics: no
_site_root: /~philippe/hw/statamic/
_site_url: /hw/statamic/